version: 2.1
workflows:
  main:
    jobs:
      - unit:
          filters:
            branches:
              ignore:
                - gh-pages
            tags:
              only: /.*/

job-references:
  env: &env
    docker:
      - image: julia:latest

  restore_julia: &restore_julia
    keys:
      - deps-{{ checksum "Manifest.toml" }}
      - deps-

  install_julia: &install_julia
    name: Install Julia dependencies
    command: julia --project -e 'using Pkg; Pkg.instantiate()'

  save_julia: &save_julia
    key: deps-{{ checksum "Manifest.toml" }}
    paths:
      - ~/.julia/compiled
      - ~/.julia/packages

jobs:
  unit:
    <<: *env
    steps:
      - run:
          name: Install git
          command: |
            apt-get update
            apt-get install -y git
      - checkout

      - restore_cache: *restore_julia
      - run: *install_julia
      - save_cache: *save_julia

      - run:
          name: Run Tests
          command: julia --project --code-coverage=user test/runtests.jl
      - run:
          name: Upload Coverage Results
          command: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
